---
title: "p8105_hw1_rz2570"
author: "**Ruilian Zhang**"
date: "*9/26/2021*"
output: github_document
---

## *Problem 1*

```{r}
# create a random sample of size 10 from a standard Normal distribution
set.seed(111) # make sure to get the same result every time
random_norm = rnorm(10, mean = 0, sd = 1)

# create a  logical vector indicating whether elements of the sample are greater than 0
greater_than_0 = c(random_norm > 0)

# create a character vector of length 10
fruits = c("grape", "raspberry", "blackberry", "durian", "apple", "strawberry", "mango", "blueberry", "banana", "avocado")

# create a factor vector of length 10, with 3 different factor “levels”
sugar_level = c("low", "medium", "low", "high", "medium", "low", "medium", "high", "high", "low")
sugar_level = factor(sugar_level, levels = c("low", "medium", "high"))

# create the dataframe
df = data.frame(random_norm, greater_than_0, fruits, sugar_level)
```

```{r, message = FALSE, warning = FALSE}
# load the tidyverse package
library(tidyverse)

# try to take the mean of each variable in the dataframe
mean(pull(df, random_norm))

mean(pull(df, greater_than_0))

mean(pull(df, fruits)) # returns warning message: argument is not numeric or logical: returning NA

mean(pull(df, sugar_level)) # returns warning message: argument is not numeric or logical: returning NA
```

Mean can be taken from numeric (random_norm) and logical (greater_than_0) variables, not character (favourite_fruits) and factor (sweetness) variables.

```{r, eval = FALSE}
# applies the as.numeric function to the logical, character, and factor variables
as.numeric(greater_than_0)

as.numeric(fruits)

as.numeric(sugar_level)
```

